"""init

Revision ID: f84658e21598
Revises: 
Create Date: 2023-05-25 03:05:54.020682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84658e21598'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('postcode', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('latitude <= 90', name='max_latitude_90_constraint'),
    sa.CheckConstraint('latitude >= -90', name='min_latitude_-90_constraint'),
    sa.CheckConstraint('longitude <= 180', name='max_longitude_180_constraint'),
    sa.CheckConstraint('longitude >= -180', name='min_longitude_-180_constraint'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude', 'longitude', name='unique_latitude_longitude_constraint')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_table('cargo',
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('pick_up_location_id', sa.Integer(), nullable=False),
    sa.Column('delivery_location_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('pick_up_location_id != delivery_location_id', name='different_locations_constraint'),
    sa.CheckConstraint('weight <= 1000', name='max_weight_1000_constraint'),
    sa.CheckConstraint('weight >= 1', name='min_weight_1_constraint'),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['pick_up_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.create_table('truck',
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('VIN', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacity <= 1000', name='max_capacity_1000_constraint'),
    sa.CheckConstraint('capacity >= 1', name='min_capacity_1_constraint'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('VIN')
    )
    op.create_index(op.f('ix_truck_id'), 'truck', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_id'), table_name='truck')
    op.drop_table('truck')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_table('cargo')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
